name: MacOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: pip3 install selenium webdriver-manager
    - name: webdriver-manager-version
      run: pip3 show webdriver-manager
    - name: run-sample
      run: python3 sample.py
