name: Ubuntu Opera CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install-selenium
      run: pip install selenium webdriver-manager
    - name: webdriver-manager-version
      run: pip show webdriver-manager
    - name: install-opera
      run: sudo apt-get install opera-stable
    - name: opera-version
      run: opera --version
    - name: run-sample
      run: python3 sample-opera.py
