name: Ubuntu Firefox CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: uninstall-firefox-snap
      run: sudo snap remove firefox
    - name: uninstall-firefox
      run: sudo remove firefox
#    - name: update-apt-get
#      run: sudo apt-get update
#    - name: upgrade-apt-get
#      run: sudo apt-get upgrade
#    - name: install-libgtk
#      run: sudo apt install libgtk-3-0
    - name: add-mozilla-source
      run: sudo add-apt-repository ppa:mozillateam/ppa
    - name: alter-firefox-package-priority
      run: sudo sh alter-firefox-package-priority.sh
    - name: install-firefox
      run: sudo apt install firefox -y
    - name: install
      run: pip install selenium selenium-firefox webdriver-manager
    - name: webdriver-manager-version
      run: pip show webdriver-manager
    - name: firefox-version
      run: firefox --version
    - name: run-sample
      run: python3 sample-firefox.py
