name: Ubuntu Opera CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: upgrade-pip
      run: pip install --upgrade pip
    - name: install-selenium
      run: pip install selenium webdriver-manager
    - name: webdriver-manager-version
      run: pip show webdriver-manager
    - name: add-opera-pointer
      run: sudo sh -c 'echo "deb http://deb.opera.com/opera/ stable non-free" >> /etc/apt/sources.list.d/opera.list'
    - name: install-opera-key
      run: wget http://deb.opera.com/archive.key -q -O - | sudo apt-key add -
    - name: update-apt-get
      run: sudo apt-get update
    - name: install-opera
      run: sudo apt-get install opera
    - name: opera-version
      run: opera --version
    - name: run-sample
      run: python3 sample-opera.py
