name: Windows Chrome CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: pip install selenium webdriver-manager
    - name: webdriver-manager-version
      run: pip show webdriver-manager
    - name: run-sample
      run: python3 sample.py
